/*! \file talker.c
 *  \brief This file is an example of cROS usage implementing a publisher and a service caller, which
 *         Can be used together with listener to prove the operation of message transmissions and service
 *         calls between two nodes.
 *
 *  It creates a publisher to the topic /chatter. Each 10ms the callback function callback_pub() is
 *  executed composing a string that is sent to the subscriber through a message of this topic.
 *  This node also implements a caller of the service /sum. Each 20ms the service is called:
 *  First the callback function callback_srv_add_two_ints is executed with call_resp_flag parameter set to 0,
 *  in this way two 64bit integers are generated by the function, which are sent to the service provider as
 *  service call parameters. The result of the service call (sum of the integers) is sent to the service
 *  caller and the callback function is executed again receiving the result with the call_resp_flag
 *  parameter set to 1.
 *  When the number of service calls or published messages is 100 the ROS node exits and the program finishes.
 */
#include <cros.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/time.h>

CrosNode *node; //! Pointer to object storing the ROS node. This object includes all the ROS node state variables
unsigned char exit_flag = 0; //! ROS node loop exit flag. When set to 1 the cRosNodeStart() function exits

// This callback will be invoked when it's our turn to publish a new message
static CallbackResponse callback_pub(cRosMessage *message, void* data_context)
{
  static int count = 0;
  char buf[1024];
  // We need to index into the message structure and then assign to fields
  cRosMessageField *data_field = cRosMessageGetField(message, "data");
  if(data_field)
  {
    snprintf(buf, sizeof(buf), "hello world %d", count);
    if(cRosMessageSetFieldValueString(data_field, buf) == 0)
    {
      ROS_INFO(node, "%s\n", buf);
    }
  }

  if(++count > 100) exit_flag=1;
  return 0;
}

static CallbackResponse callback_srv_add_two_ints(cRosMessage *request, cRosMessage *response, int call_resp_flag, void* context)
{
  static int count = 0;
  cRosMessageField *a_field = cRosMessageGetField(request, "a");
  cRosMessageField *b_field = cRosMessageGetField(request, "b");

  a_field->data.as_int64=7;
  b_field->data.as_int64=8;

  cRosMessageField *sum_field = cRosMessageGetField(response, "sum");

  if(call_resp_flag)
    ROS_INFO(node, "Service add 2 ints response: %lld (count: %i)\n", (long long)sum_field->data.as_int64, count);
  else
    ROS_INFO(node, "Service add 2 ints call arguments: {a: %lld, b: %lld}\b\n", (long long)a_field->data.as_int64, (long long)b_field->data.as_int64);

  if(++count > 100) exit_flag=1;
  return 0;
}

int main(int argc, char **argv)
{
  // We need to tell our node where to find the .msg files that we'll be using
  char path[1024];

  getcwd(path, sizeof(path));
  strncat(path, "/rosdb", sizeof(path));
  // Create a new node and tell it to connect to roscore in the usual place
  node = cRosNodeCreate("/talker", "127.0.0.1", "127.0.0.1", 11311, path, NULL);
  // Create a publisher and request that the associated callback be invoked every 100ms (10Hz)

  if(cRosApiRegisterPublisher(node, "/chatter","std_msgs/String", 10, callback_pub, NULL, NULL) < 0)
  {
    printf("cRosApiRegisterPublisher failed; did you run this program one directory above 'rosdb'?\n");
    return EXIT_FAILURE;
  }

  if(cRosApiRegisterServiceCaller(node,"/sum","roscpp_tutorials/TwoInts", 20, callback_srv_add_two_ints, NULL, NULL, 1, 1) < 0)
  {
    printf("cRosApiRegisterServiceCaller failed; did you run this program one directory above 'rosdb'?\n");
    return EXIT_FAILURE;
  }

  // Run the main loop
  struct timeval start_time, end_time;
  float elapsed_time;

  gettimeofday(&start_time, NULL);
  cRosNodeStart( node, &exit_flag );
  gettimeofday(&end_time, NULL);

  elapsed_time = (end_time.tv_sec - start_time.tv_sec) * 1000.0;      // sec to ms
  elapsed_time += (end_time.tv_usec - start_time.tv_usec) / 1000.0;   // us to ms

  // All done
  cRosNodeDestroy( node );
  printf("Elapsed time: %fms\n", elapsed_time);

  return EXIT_SUCCESS;
}
