BUILD
=====

Create a catkin environment following the guide at:

    http://wiki.ros.org/ROS/Tutorials/InstallingandConfiguringROSEnvironment

Assume the catkin workspace is located at "~/catkin_ws", link
the current folder in the catkin source folder, for example:

    $ ln -s ~/cros/gripping_robot ~/catkin_ws/src

To compile and install do the following:

    $ cd ~/catkin_ws
    $ catkin_make
    $ catkin_make install

To test launch:
    $ rosrun gripping_robot gripperstatus_talker
    $ rosrun gripping_robot gripperjoints_talker
    $ rosrun gripping_robot test_services

