BUILD
=====

Create a catkin environment following the guide at:

    http://wiki.ros.org/ROS/Tutorials/InstallingandConfiguringROSEnvironment

Assume the catkin workspace is located at "~/catkin_ws", link
the current folder in the catkin source folder, for example:

    $ ln -s ~/itr-cros/cros_testbed ~/catkin_ws/src

To compile and install do the following:

    $ cd ~/catkin_ws
    $ catkin_make
    $ catkin_make install
